baseURL = "/"
languageCode = "en-us"
Title = "example.org"
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
copyright = "© Your Name here"
summaryLength = 10

[permalinks]
  blog = "blog/:slug/"

[params]
  email = "nobody@example.com"
  rss_icon = "/Rss-feed.svg"
  pen_icon = "/pen.svg"
  home_loaf = "/bread_loaf.jpg"
  home_crumb = "/bread_crumb.jpg"
  AuthorName = "Your Name"
  logoUrl = "logo.png"
  thumbMaxPx = "75x75"
  slideMaxPx = "150x150"
  bodyMaxPx = "600x600"

[markup.goldmark.renderer]
  unsafe = true