name = "But Not Simpler"
license = "GPL 3"
licenselink = "https://github.com/saufrecht/hugo-theme-but-not-simpler/blob/master/LICENSE"
description = "A CSS-only, no javascript, no SASS, responsive Hugo theme with solarized colors and automatic dark mode."
homepage = "https://github.com/saufrecht/hugo-theme-but-not-simpler/"
tags = [
        "hugo",
        "no javascript",
        "no js",
        "css only",
        "responsive",
        "dark mode",
        "prefers-color-scheme"
        ]
features = []
min_version = "0.41.0"

[author]
  name = "S Aufrecht"
  homepage = "https://aufrecht.org"
